name: "ensure-conventional-commits"
description: "checks that the commits in a pull request follow conventional commits"
inputs:
  settings-file:
    description: "json files with the settings for custom conventional commit type and scopes"
    required: false

runs:
  using: "composite"
  steps:
    - name: 'Validate Custom Conventional Commit File'
      if: ${{ hashFiles(inputs.settings-file) != '' }}
      env:
        SETTINGS_FILE: ${{ inputs.settings-file }}
      run: |
        node ${{ github.action_path }}/validate-settings-gh-action.js
      shell: bash
    - name: 'Validate Commits Provided'
      env:
        SETTINGS_FILE: ${{ inputs.settings-file }}
      run: |
        node ${{ github.action_path }}/main.js
      shell: bash
